Repository toango123zx/PBL6-Travalid, pull requests merged in 2023-11, with the labels that each got.

#4 feat (All user): Sign In
  BackEnd/package-lock.json
  BackEnd/package.json
  BackEnd/src/.env.example
  BackEnd/src/config/.gitkeep
  BackEnd/src/config/envApp.js
  BackEnd/src/config/prismaDatabase.js
  BackEnd/src/controllers/authController.js
  BackEnd/src/database/insert/product.js
  BackEnd/src/database/insert/user.js
  BackEnd/src/database/prisma/schema.prisma
  BackEnd/src/helpers/.gitkeep
  BackEnd/src/helpers/authHelper.js
  BackEnd/src/helpers/hash.js
  BackEnd/src/index.js
  BackEnd/src/middlewares/.gitkeep
  BackEnd/src/routes/auth.js
  BackEnd/src/routes/index.js
  BackEnd/src/services/.gitkeep
  BackEnd/src/services/userService.js
Labels: feat

#5 feat (Supplier and traveller): Sign up - BackEnd
  BackEnd/src/.env.example
  BackEnd/src/config/envSupplier.js
  BackEnd/src/controllers/authController.js
  BackEnd/src/helpers/hash.js
  BackEnd/src/middlewares/authMiddleware.js
  BackEnd/src/routes/auth.js
  BackEnd/src/services/userService.js
  BackEnd/src/validation/authValidation.js
Labels: feat

#6 feat (All user): API refresh token login and verify token Sign in
  BackEnd/src/controllers/authController.js
  BackEnd/src/database/Query/index.js
  BackEnd/src/helpers/authHelper.js
  BackEnd/src/middlewares/authMiddleware.js
  BackEnd/src/routes/auth.js
Labels: feat

#9 feat (Traveller and user and admin): Bill
  BackEnd/src/controllers/billController.js
  BackEnd/src/controllers/userController.js
  BackEnd/src/database/insert/product.js
  BackEnd/src/helpers/billHelper.js
  BackEnd/src/routes/bill.js
  BackEnd/src/routes/index.js
  BackEnd/src/routes/user.js
  BackEnd/src/services/billService.js
  BackEnd/src/services/discountService.js
  BackEnd/src/services/productService.js
  BackEnd/src/services/scheduleProductService.js
Labels: feat

#11 Fix (User) - Add token expiration notification (access token and refresh token)
  BackEnd/src/controllers/authController.js
  BackEnd/src/controllers/userController.js
  BackEnd/src/helpers/authHelper.js
  BackEnd/src/middlewares/authMiddleware.js
  BackEnd/src/routes/user.js
  BackEnd/src/services/userService.js
  BackEnd/src/validation/authValidation.js
Labels: bug

#12 feat (admin): Add sign up for admin
  BackEnd/src/controllers/authController.js
  BackEnd/src/routes/auth.js
  BackEnd/src/validation/authValidation.js
Labels: feat

#13 fix: sign up - validation
  BackEnd/package-lock.json
  BackEnd/package.json
  BackEnd/src/controllers/authController.js
  BackEnd/src/index.js
  BackEnd/src/routes/auth.js
  BackEnd/src/validation/authValidation.js
Labels: good first issue

#16 fix (user): Bill
  BackEnd/src/controllers/billController.js
  BackEnd/src/helpers/billHelper.js
  BackEnd/src/routes/bill.js
  BackEnd/src/services/billService.js
  BackEnd/src/services/scheduleProductService.js
Labels: fix

#17 feat (traveller): Cart
  BackEnd/src/controllers/cartController.js
  BackEnd/src/helpers/cartHelper.js
  BackEnd/src/routes/cart.js
  BackEnd/src/routes/index.js
  BackEnd/src/services/cartService.js
  BackEnd/src/services/scheduleProductService.js
Labels: feat
