Repository toango123zx/PBL6-Travalid, pull requests merged in 2023-12, with the labels that each got.

#18 fix (database): add column in product and contact
  BackEnd/src/database/prisma/schema.prisma
Labels: fix

#19 doc: doc API Authentication and discount
  BackEnd/nodemon.json
  BackEnd/package-lock.json
  BackEnd/package.json
  BackEnd/src/common/swagger/apiDocs.yaml
  BackEnd/src/common/swagger/auth.yaml
  BackEnd/src/common/swagger/definition.yaml
  BackEnd/src/common/swagger/discount.yaml
  BackEnd/src/common/swagger/product.yaml
  BackEnd/src/index.js
  README.md
Labels: documentation

#21 feat (user): API for user information
  BackEnd/src/controllers/userController.js
  BackEnd/src/routes/index.js
  BackEnd/src/routes/user.js
  BackEnd/src/services/userService.js
  BackEnd/src/validation/authValidation.js
Labels: feat

#23 ref(user): Change query database product from controller to service + validate product
  BackEnd/package-lock.json
  BackEnd/package.json
  BackEnd/src/.env.example
  BackEnd/src/config/envApp.js
  BackEnd/src/controllers/ProductController.js
  BackEnd/src/controllers/authController.js
  BackEnd/src/controllers/billController.js
  BackEnd/src/controllers/discountController.js
  BackEnd/src/database/prisma/schema.prisma
  BackEnd/src/helpers/productHelper.js
  BackEnd/src/helpers/scheduleHelper.js
  BackEnd/src/routes/product.js
  BackEnd/src/services/discountService.js
  BackEnd/src/services/productService.js
  BackEnd/src/services/scheduleProductService.js
  BackEnd/src/validation/authValidation.js
Labels: refactor

#25 fix(user): Upload and update image
  BackEnd/src/controllers/userController.js
  BackEnd/src/database/prisma/schema.prisma
  BackEnd/src/helpers/imageHelper.js
  BackEnd/src/routes/user.js
  BackEnd/src/services/destroyService.js
  BackEnd/src/services/userService.js
  BackEnd/src/validation/userValidation.js
Labels: fix

#26 feat(user): upload image or images to firebase
  BackEnd/package-lock.json
  BackEnd/src/controllers/userController.js
  BackEnd/src/helpers/imageHelper.js
  BackEnd/src/routes/user.js
  BackEnd/src/services/destroyService.js
  BackEnd/src/validation/imageValidation.js
  BackEnd/src/validation/userValidation.js
Labels: feat, good first issue

#27 fix(user): discount validation
  BackEnd/src/controllers/discountController.js
  BackEnd/src/database/prisma/schema.prisma
  BackEnd/src/routes/discount.js
  BackEnd/src/validation/discountValidation.js
  BackEnd/src/validation/userValidation.js
Labels: feat

#28 fix(user): add code discount
  BackEnd/src/.env.example
  BackEnd/src/config/envApp.js
  BackEnd/src/controllers/discountController.js
  BackEnd/src/routes/discount.js
  BackEnd/src/services/discountService.js
  BackEnd/src/validation/discountValidation.js
Labels: fix

#30 feat(user): rate
  BackEnd/src/.env.example
  BackEnd/src/config/envApp.js
  BackEnd/src/controllers/rateController.js
  BackEnd/src/database/prisma/schema.prisma
  BackEnd/src/middlewares/authMiddleware.js
  BackEnd/src/routes/index.js
  BackEnd/src/routes/rate.js
  BackEnd/src/services/rateService.js
  BackEnd/src/validation/rateValidation.js
Labels: feat
